// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/MegaBlackLabel/go-clean-architecture-practice/adapter/controllers"
	memory2 "github.com/MegaBlackLabel/go-clean-architecture-practice/adapter/gateways/memory"
	"github.com/MegaBlackLabel/go-clean-architecture-practice/infrastructure/handler"
	"github.com/MegaBlackLabel/go-clean-architecture-practice/infrastructure/memory"
	"github.com/MegaBlackLabel/go-clean-architecture-practice/usecase/interactor"
	"github.com/MegaBlackLabel/go-clean-architecture-practice/utils/logs/lggr"
)

// Injectors from wire.go:

func InitialiseApps() handler.UserHandler {
	userList := memory.NewUserMemory()
	userRepository := memory2.NewUserRepository(userList)
	userInteractor := interactor.NewUserInteractor(userRepository)
	logger := lggr.NewLogger()
	userController := controllers.NewUserController(userInteractor, logger)
	userHandler := handler.NewUserHandler(userController, logger)
	return userHandler
}
